database:
  host: localhost
  port: 5432
  user: postgres
  password: Lalitha@1408
  dbname: ecommerce_dw

paths:
  raw_data: data/raw
  staging_data: data/staging
  processed_data: data/processed

data_generation:
  customers: 100
  products: 50
  transactions: 500
  start_date: "2024-01-01"
  end_date: "2024-12-31"
